<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'JMS\Payment\PaypalBundle\Plugin\ExpressCheckoutPlugin' shared service.

include_once $this->targetDirs[3].'\\vendor\\jms\\payment-core-bundle\\JMS\\Payment\\CoreBundle\\Plugin\\PluginInterface.php';
include_once $this->targetDirs[3].'\\vendor\\jms\\payment-core-bundle\\JMS\\Payment\\CoreBundle\\Plugin\\AbstractPlugin.php';
include_once $this->targetDirs[3].'\\vendor\\jms\\payment-paypal-bundle\\JMS\\Payment\\PaypalBundle\\Plugin\\ExpressCheckoutPlugin.php';

return $this->services['JMS\Payment\PaypalBundle\Plugin\ExpressCheckoutPlugin'] = new \JMS\Payment\PaypalBundle\Plugin\ExpressCheckoutPlugin(NULL, NULL, ${($_ = isset($this->services['payment.paypal.client']) ? $this->services['payment.paypal.client'] : $this->load('getPayment_Paypal_ClientService.php')) && false ?: '_'}, NULL, NULL);
