<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJpzxf3d\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJpzxf3d/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJpzxf3d.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJpzxf3d\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJpzxf3d\appDevDebugProjectContainer([
    'container.build_hash' => 'Jpzxf3d',
    'container.build_id' => '271b18ba',
    'container.build_time' => 1549406790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJpzxf3d');
