<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKz9hj9n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKz9hj9n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKz9hj9n.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKz9hj9n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKz9hj9n\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kz9hj9n',
    'container.build_id' => 'd612021d',
    'container.build_time' => 1548854956,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKz9hj9n');
