<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRkeqx8n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRkeqx8n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRkeqx8n.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRkeqx8n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRkeqx8n\appDevDebugProjectContainer([
    'container.build_hash' => 'Rkeqx8n',
    'container.build_id' => '2b4c6ac2',
    'container.build_time' => 1549407273,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRkeqx8n');
